apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-system

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - ../api/deployment.yaml
  - ../api/service.yaml
  - ../api/hpa.yaml
  - ../api/pdb.yaml
  - ../api/hf-cache-pvc.yaml
  - ../qdrant/statefulset.yaml
  - ../qdrant/service.yaml
  - ../qdrant/pvc.yaml
  - ../redis/deployment.yaml
  - ../redis/service.yaml
  - ../ingress/ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: clip-image-search
  app.kubernetes.io/managed-by: kustomize
